### ISSUE TITLE
`MIPNodeCtx::add_lazy()` is not working correctly?

### ISSUE THREAD

**Issue by sbeyer** [ykrist/rust-grb#3]
**edit:** I am currently trying to find a minimal example... maybe this gets me down to the cause of my problem and I'll close this issue. Ignore this as long as I did not remove this mention.

Hi,

it seems that `MIPNodeCtx::add_lazy()` is not working correctly. In my original code it seems to simply ignore the constraints added. Note that `MIPSolCtx::add_lazy()` works as expected.

**edit**: I had a minimal example here which did not work for other reasons. I have not made another minimal example, but I guess the TSP example could work. Just add something like
```rust
    if let Where::MIPNode(ctx) = w {
        ctx.add_lazy(c!(/* XXX */))?;
    }
```
where `/* XXX */` should be replaced by a constraint that makes the model infeasible, like one variable `>= 2` ...
However, the model will still have the same objective value as without it although it is expected to be infeasible.

Tested with Gurobi 9.1.2 and grb 1.0.4,
not tested if the issue also occurs using C code.

**Comment by sbeyer** [comment]
The issue is clearly related to Gurobi and not to rust-grb. I have found out that with slightly different inputs, the lazy constraints are not ignored. Sorry for the noise here.

**Comment by ykrist** [comment]
I've released a new version that fixes a bug in the user cuts (not lazy constraints). 

From Gurobi's manual, 
_Your callback should be prepared to cut off solutions that violate any of your lazy constraints, including those that have already been added. Node solutions will usually respect previously added lazy constraints, but not always._ 

I think the issue here was that Gurobi assumes that lazy constraints added at MIPNODE and MIPSOL are consistent.  For example, if at MIPNODE you add a constraint which makes the model infeasible, then you may need to add this same constraint at MIPSOL again.  I don't quite understand why (perhaps because of synchronization difficulties between threads processing MIP nodes in parallel), but I've observed Gurobi treat MIPNODE lazy constraints more as "suggestions".

**Comment by sbeyer** [comment]
It's exactly that! If the relaxation is already integral, then MIPSOL is called right before MIPNODE. If MIPSOL does not add a lazy constraint, then MIPNODE's addition of lazy constraints are ignored "for performance reasons" or something... I didn't see this quirk documented in the Gurobi documentation, but I asked them and they told me.
